/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.luizalabs.simple;

import org.eclipse.jetty.server.Server;
import org.glassfish.jersey.jetty.JettyHttpContainerFactory;

import com.luizalabs.simple.common.config.AppResourceConfig;

public class App {

    private Server server;

    private App() {
        AppResourceConfig config = AppResourceConfig.getInstance();
        server = JettyHttpContainerFactory.createServer(
            config.uri(),
            config);
    }

    private void start() throws Exception {
        server.join();
        server.setStopAtShutdown(true);
    }

    private void stop() throws Exception {
        if (server != null) {
            server.stop();
        }
    }

    public static void main(String[] args) throws Exception {
        App app = new App();
        try {
            app.start();
        } finally {
            app.stop();
        }
    }
}
